export const Constants = {
    CANVAS_WIDTH: 800,
    CANVAS_HEIGHT: 600,
    STATION_SIZE: 40,
    STATION_OUTLINE: 10,
    EDGE_WIDTH: 15,
    // PEOPLE
    PERSON_SIZE: 12.5,
    PERSON_XOFFSET: 10,
    PERSON_YOFFSET: 10,
    PERSON_OFFSET: 5, // TODO REMOVE X and Y OFFSET, just use this
    // TRAINS
    TRAIN_LENGTH: 50,
    TRAIN_ASPECT: 0.6,
    PASSENGER_SIZE_MULTIPLIER: 0.7,
    PASSENGER_LIGHTNESS_FACTOR: 0.7,
};